"""updated user table

Revision ID: 157d8c6add79
Revises: 3a99d333887e
Create Date: 2023-02-27 19:28:03.278615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157d8c6add79'
down_revision = '3a99d333887e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
