"""updated user table and added admin role

Revision ID: 322dcb83c6da
Revises: d05552bc20b6
Create Date: 2023-02-27 16:11:46.816472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322dcb83c6da'
down_revision = 'd05552bc20b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.drop_column('users', 'is_candidate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_candidate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
