"""Create party table

Revision ID: 636a1ea2eca5
Revises: 1cd900429e35
Create Date: 2023-02-27 11:38:24.716206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636a1ea2eca5'
down_revision = '1cd900429e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party_logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party')
    # ### end Alembic commands ###
