"""updated user table

Revision ID: 73c2934207e3
Revises: 322dcb83c6da
Create Date: 2023-02-27 19:02:47.165796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c2934207e3'
down_revision = '322dcb83c6da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lga', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lga')
    # ### end Alembic commands ###
