"""empty message

Revision ID: 8a63ffed052e
Revises: 25ac97cc71a5
Create Date: 2023-02-28 11:22:04.110571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a63ffed052e'
down_revision = '25ac97cc71a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "mobile_no", type_=sa.CHAR(length=11))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "mobile_no", type_=sa.INTEGER)
    pass
    # ### end Alembic commands ###
