"""updated user table

Revision ID: db16bc81133f
Revises: 73c2934207e3
Create Date: 2023-02-27 19:23:16.071174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db16bc81133f'
down_revision = '73c2934207e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
